# COLOUR CONSTANTS
COLOUR_RED = '\033[91m'
COLOUR_GREEN = '\033[92m'
COLOUR_END = '\033[0m'
COLOUR_BLUE = '\033[94m'

# DEFAULT ADDRESSES
DEFAULT_SERVER_PORT = 65000
DEFAULT_SERVER_ADDRESS = "127.0.0.1"


# PACKET CONSTANTS
PAYLOAD_SIZE = 4087
HEADER_SIZE = 9

PACKET_SIZE = HEADER_SIZE + PAYLOAD_SIZE


#DEFAULT OPERATIONS
DOWNLOAD = 1
UPLOAD = 0

# DEFAULT TIMEOUT
TIMEOUT = 10

# DEFAULT RETRIES
RETRIES = 10
SYN_RETRIES = 3

#PROTOCOLS
SAW_PROTOCOL = "saw" #Stop and Wait
GBN_PROTOCOL = "gbn" #Go Back N
DEFAULT_PROTOCOL = SAW_PROTOCOL




