# COLOUR CONSTANTS
COLOUR_RED = '\033[91m'
COLOUR_GREEN = '\033[92m'
COLOUR_END = '\033[0m'
COLOUR_BLUE = '\033[94m'

# DEFAULT ADDRESSES
DEFAULT_SERVER_PORT = 65000
DEFAULT_SERVER_ADDRESS = "127.0.0.1"


# PACKET CONSTANTS
PAYLOAD_SIZE = 4087
HEADER_SIZE = 9

PACKET_SIZE = HEADER_SIZE + PAYLOAD_SIZE


#DEFAULT OPERATIONS
DOWNLOAD = 1
UPLOAD = 0

# DEFAULT TIMEOUT
TIMEOUT_SOCKET = 0.1
TIMEOUT_QUEUE = 0.1
#TIMEOUT_SERVER_SOCKET = 10
#TIMEOUT_ACK = 0.5

# DEFAULT RETRIES
RETRIES = 10
SYN_RETRIES = 3

#PROTOCOLS
SAW_PROTOCOL = "saw" #Stop and Wait
GBN_PROTOCOL = "gbn" #Go Back N
DEFAULT_PROTOCOL = SAW_PROTOCOL


# DEFAULT WINDOW SIZE
WINDOW_SIZE = 6

# DEFAULT MAX RETRANSMITS
RETRIES = 10
MAX_RETRANSMITS = 10


FIN = 0
OK = 1

# ACK CONSTANTS
MAX_REPEATED_ACKS=3